<?php

namespace TV\FindyourbandBundle\Repository;

/**
 * ImageInstruRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageInstruRepository extends \Doctrine\ORM\EntityRepository
{
}
