<?php

namespace TV\FindyourbandBundle\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLevels()
    {
        $query = $this->createQueryBuilder('a')
            ->orderBy('a.id', 'ASC')
            ->getQuery()
        ;

        return $query->getResult();
    }
}
